Repository UmaSupporter/UmaSupporter.WebClient, pull requests merged in 2021-04, with the labels that each got.

#10 feat: default sort by rare degree
  src/common/utils.ts
  src/components/SupportCardList/SupportCardListContainer.tsx
Labels: enhancement

#16 fix: transfer repository
  README.md
  src/pages/Main/Main.tsx
Labels: documentation

#17 fix: move node-sass to dependencies from dev
  package.json
Labels: bug

#24 fix: github url
  src/pages/Main/Main.tsx
Labels: bug

#26 feature: 스킬 일본어 한국어 병기
  codegen.yml
  package.json
  src/components/EventDetail/Effect/Effect.tsx
  src/components/EventDetail/Effect/Skill.tsx
  src/components/EventDetail/EventDetail.tsx
  src/generated/graphql.tsx
  yarn.lock
Labels: enhancement

#27 fix: only one filter
  src/views/CardList/CardListReducer.tsx
Labels: enhancement

#25 enhanced uxs
  package.json
  src/components/CardFilter/CardTypeFilterComponent.scss
  src/components/EventDetail/EventDetail.scss
  src/components/SelectedCardList/SelectedCardList.scss
  src/components/SupportCardDetail/SupportCardDetail.scss
  src/components/SupportCardDetail/SupportCardDetailNotExistComponent.tsx
  src/components/SupportCardList/SupportCard/SupportCard.scss
  src/components/SupportCardList/SupportCard/SupportCard.tsx
  src/components/SupportCardList/SupportCardList.scss
  src/components/UmaDetail/UmaDetailComponent.scss
  src/components/UmaDetail/UmaDetailNotExistComponent.tsx
  src/components/UmaList/UmaComponent/UmaComponent.scss
  src/components/UmaList/UmaList.scss
  src/components/common/Hero/Hero.scss
  src/components/common/Hero/Hero.tsx
  src/components/common/styles/Card.scss
  src/components/common/styles/Palette.scss
  src/img/dislike_sm.png
  src/img/like_sm.png
  src/pages/Main/Main.scss
  src/pages/Main/Main.tsx
  src/views/CardList/CardList.scss
  yarn.lock
Labels: enhancement

#28 Save favorite cards to localstorage
  src/pages/Main/Main.tsx
Labels: enhancement

#29 feat: skill tooltip
  package.json
  src/components/EventDetail/Effect/Skill.tsx
  yarn.lock
Labels: enhancement

#31 fix: donation page
  src/pages/Main/Main.tsx
Labels: bug

#32 Show buff detail
  public/index.html
  src/components/EventDetail/Effect/Buff.scss
  src/components/EventDetail/Effect/Buff.tsx
  src/components/EventDetail/Effect/Effect.tsx
  src/components/EventDetail/Effect/EffectFacade.tsx
  src/components/EventDetail/Effect/Skill.scss
  src/components/EventDetail/Effect/Skill.tsx
  src/generated/graphql.tsx
Labels: enhancement

#34 feat: translate event title
  src/components/SupportCardDetail/SupportCardDetail.tsx
  src/components/SupportCardDetail/SupportCardDetailContainer.tsx
  src/components/UmaDetail/UmaDetailComponent.tsx
  src/components/UmaDetail/UmaDetailContainer.tsx
  src/components/common/fragments.ts
  src/generated/graphql.tsx
  src/types/index.ts
Labels: translate

#35 fix: proper layout for selectedCard
  src/components/CardFilter/CardTypeFilterComponent.scss
  src/components/SelectedCardList/SelectedCard/SelectedCard.scss
  src/components/SelectedCardList/SelectedCardList.scss
  src/components/SupportCardList/SupportCard/SupportCard.scss
  src/components/SupportCardList/SupportCardList.scss
  src/components/UmaList/UmaComponent/UmaComponent.scss
  src/components/UmaList/UmaList.scss
  src/components/common/Hero/Hero.scss
  src/components/common/styles/Card.scss
Labels: bug

#40 fix: donation
  src/pages/Main/Main.tsx
Labels: bug

#42 fix: material ui overriding
  src/components/GeneralChoiceDialog/GeneralChoiceDialog.scss
  src/components/GeneralChoiceDialog/GeneralChoiceDialog.tsx
  src/components/common/styles/App.scss
  src/components/common/styles/Palette.scss
  src/components/common/styles/Typography.scss
  src/components/common/styles/theme/dark.scss
  src/components/common/styles/theme/light.scss
  src/pages/Main/Main.scss
Labels: bug
